apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-api-gateway
  namespace: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
        app: hello-world
        run: api-gateway
    spec:
      containers:
      - name: apigateway
        image: cloud.canister.io:5000/ktogias/helloworld:helloworldapigateway-0.1.1
        env:
        - name: HELLO_SERVICE_URL
          value: hello-service.helloworld.svc.cluster.local
        - name: WORLD_SERVICE_URL
          value: world-service.helloworld.svc.cluster.local
      imagePullSecrets:
      - name: registry-canisterio
      
---

apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: helloworld
spec:
  selector:
    run: api-gateway
  ports:
  - name: http 
    port: 80
    targetPort: 80
    
---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hwapi-ms-ktogias-gr-credential-staging
  namespace: istio-system
  labels:
    use-http01-solver: "true"
  annotations:
          #  cert-manager.io/issue-temporary-certificate: "true"
          acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  dnsNames:
    - hwapi.ms.ktogias.gr
  secretName: hwapi-ms-ktogias-gr-credential-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: hwapi.ms.ktogias.gr

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: hwapi-ms-ktogias-gr-gateway
  namespace: helloworld
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: hwapi-ms-ktogias-gr-credential-staging
      # privateKey: sds
      # serverCertificate: sds
    hosts:
    - "hwapi.ms.ktogias.gr"
    
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hwapi-ms-ktogias-gr
  namespace: helloworld
spec:
  hosts:
  - "hwapi.ms.ktogias.gr"
  gateways:
  - hwapi-ms-ktogias-gr-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: api-gateway
      