apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-ui
  namespace: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: helloworldui
        image: cloud.canister.io:5000/ktogias/helloworld:helloworldui-0.1.0
      imagePullSecrets:
      - name: registry-canisterio
